---
- hosts: all
  tasks:
    - name: Instalando apache debian family
      package:
         name: apache2
         state: latest
      when: ansible_os_family == 'Debian'

    - name: Instanando apache RedHat
      package:
         name: httpd
         state: latest
      when: ansible_os_family == 'RedHat'  
 


...
