---
- name: Instalando pacotes
  hosts: devops docker
  tasks: 
    - name: Pacotes basicos do sistema
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      with_items:
        - vim
        - nano
        - sl
        - ccze
        - dnsutils


...
