---
- name: Criar usuarios
  hosts: all
  vars:
    - username: sysadmin


  tasks:
    - name: Criando usuario nos servidores
      user:
        name: "{{ username }}"
        shell: /bin/bash
        createhome: yes
...
