---
# Variable setup.
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"


# Setup/install tasks.
- include: setup-centos.yml
  when: ansible_os_family == 'RedHat'

- include: setup-debian.yml
  when: ansible_os_family == 'Debian'
