---
 
- name: 'Pacotes básicos do sistema'
  apt: 
    name: "{{ item }}"
    state: present
    update_cache: yes
    become: true
  with_items:
    - unzip
    - vim
    - wget 
    - sl
    - ccze
    - dnsutils
    - build-essential
    - git
    - postfix
    - gcc
    - g++
    - curl
    - make
    - htop
    - nmap
    - php-pear       
    - php5-cli 
    - php5-curl 	
    - php5-gd 	
    - php5-json 	
    - php5-imap 	
    - php5-mcrypt 	
    - php5-mongo 	
    - php5-mysql 	
    - php5-redis 	
    - php5-memcached
    - php5-intl	
    - php5-sqlite    
    - php5-apcu      
    - php5-xmlrpc 
